"""Generate the pre-build browser check from the exact asset registry used by the app."""
from pathlib import Path
import json,html
base=Path(__file__).resolve().parents[1]
assets=json.loads((base/'app/src/main/assets/site-assets.json').read_text())
labels={'order_active':'Ordem Maior • EM ANDAMENTO','order_completed':'Ordem Maior • VITÓRIA','order_failed':'Ordem Maior • DERROTA','reward_medalhas':'Recompensa • MEDALHAS','human':'Símbolo • Super Terra','earth':'Planeta • Super Terra','defense':'Operação • DEFESA','liberation':'Operação • LIBERTAÇÃO','city':'Região • cidade/assentamento','factory':'Região • megafábrica'}
cards=[]
for key,paths in assets.items():
 for i,path in enumerate(paths):
  url='https://helldivers-br.pages.dev/'+path
  cards.append(f'''<article class="{'banner' if key.startswith('order_') else ''}"><h2>{html.escape(labels.get(key,key))}{' (alternativa)' if i else ''}</h2><div class="picture"><img src="{html.escape(url,quote=True)}" alt="{html.escape(labels.get(key,key))}" loading="eager"></div><p class="status">Carregando…</p><code>{html.escape(path)}</code><a target="_blank" rel="noopener" href="{html.escape(url,quote=True)}">Abrir imagem original ↗</a></article>''')
page='''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HELLDIVERS-BR • Conferência antes de compilar</title>
<style>*{box-sizing:border-box}body{margin:0;background:#101214;color:#eee;font:16px Arial,sans-serif}main{max-width:1180px;margin:auto;padding:24px}h1{color:#d7d52c;font-size:28px}p{line-height:1.6}aside{background:#222814;padding:16px;border:1px solid #747828;border-radius:12px;margin:20px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(275px,1fr));gap:16px}article{background:#1b1d20;border:1px solid #3b4147;border-radius:14px;overflow:hidden;padding:16px}h2{font-size:16px;min-height:36px}.picture{height:170px;display:flex;align-items:center;justify-content:center;background:#080b10;border-radius:9px;overflow:hidden}.picture img{max-width:100%;max-height:100%;object-fit:contain}.banner .picture{height:220px}code{display:block;overflow-wrap:anywhere;font-size:12px;color:#bfc3ca;margin:12px 0}a{color:#d7d52c;font-size:13px}.ok{color:#7dec9c}.error{color:#ffab79}button{background:#d7d52c;border:0;padding:12px 18px;border-radius:7px;font-weight:bold;cursor:pointer}.status{font-size:13px;min-height:40px}</style>
<main><h1>Conferir as imagens antes de compilar</h1><p>Este painel usa o mesmo <b>site-assets.json</b> do aplicativo. Abra este arquivo no Chrome com internet. As três primeiras imagens correspondem aos estados da Ordem Maior; a medalha é o arquivo SVG original, não um emoji.</p><aside><b>O que significa aprovado?</b><br>1. O indicador fica verde quando a imagem realmente carrega.<br>2. Confira visualmente se a arte corresponde ao título: andamento, vitória e derrota.<br>3. Se a imagem abrir mas estiver errada, corrija o arquivo ou seu caminho no cadastro antes de compilar.<br>Um indicador verde confirma carregamento, não comprova que a arte está semanticamente correta. Isto é uma conferência das imagens; o APK ainda precisa ser testado no Android.</aside><button onclick="location.reload()">CONFERIR NOVAMENTE</button><p id="summary" aria-live="polite">Carregando imagens…</p><section class="grid">'''+''.join(cards)+'''</section><p>As alternativas são caminhos de reserva já definidos no site. Nas imagens sem alternativa, a falta do arquivo será mostrada como erro, sem substituir a arte por outra imagem.</p></main>
<script>
const cards=[...document.querySelectorAll('article')];
function summary(){const ok=cards.filter(c=>c.dataset.result==='ok').length;const error=cards.filter(c=>c.dataset.result==='error').length;document.getElementById('summary').textContent=`${ok} imagens carregadas • ${error} falhas • ${cards.length-ok-error} aguardando`;}
for(const card of cards){const img=card.querySelector('img'),status=card.querySelector('.status');const done=()=>{const ok=img.naturalWidth>0;card.dataset.result=ok?'ok':'error';status.className='status '+(ok?'ok':'error');status.textContent=ok?`✓ Carregou · ${img.naturalWidth} × ${img.naturalHeight} pixels`:'✕ Não carregou. Abra o original para conferir o endereço e o acesso.';summary();};img.addEventListener('load',done);img.addEventListener('error',done);if(img.complete)done();}
</script></html>'''
(base/'CONFIRIR-IMAGENS.html').write_text(page,encoding='utf-8')
print('Preview gerado a partir de',len(assets),'recursos do APK.')
